### ISSUE TITLE
Change simulink integrator from Integration: Forward Euler to Integration: Backward Euler

### ISSUE THREAD

**Issue by Kirkados** [TheElectricDream/SPOT#12]
The current integrator (Forward Euler) introduces 2 unnecessary delays in the system. For a given acceleration at timestep n, the integrated velocity is reflected in timestep n+1. Then, the position changes at timestep n+2. So, an acceleration takes 2 timesteps to be reflected in the position.

I propose we switch to Backward Euler integration because this causes the position, velocity, and acceleration signals to change at the same timestep (the way nature works).  Plus, it fixes my delay-sensitive controller :)

**Comment by TheElectricDream** [comment]
Fixed in next update.
