### ISSUE TITLE
[Bug] Thrusters Remain on after Stop Experiment

### ISSUE THREAD

**Issue by Kirkados** [TheElectricDream/SPOT#3]
Thrusters stay in most recent state when "Stop Experiment" button is pressed in GUI. Intended behaviour is to have all thrusters stop when Stop Experiment is pressed.

**Comment by TheElectricDream** [comment]
Fixed: Created a CleanShutdown model that is executed at the end of an experiment. The model ensures all thrusters and pucks are turned off.
