### ISSUE TITLE
[Bug] Automatic "Build and Run" is a safety hazard

### ISSUE THREAD

**Issue by Kirkados** [TheElectricDream/SPOT#4]
If possible, please have the default in Simulink -> Hardware Settings -> Hardware Implementation -> Target hardware resources -> Build options -> Build action be "Build" instead of "Build and Run". A platform could easily fall off the table if the user leaves the lab while waiting for the code to deploy to a platform (especially if the e-stop is pressed). Of course, this may not be possible.

**Comment by TheElectricDream** [comment]
Fix: The "Build" option is programmatically selected when the user clicks "Deploy Code". A warning is also displayed to ensure that users check that the correct build option has been selected.
