### ISSUE TITLE
[Request] Pucks need to be off before clicking "Start Experiment"

### ISSUE THREAD

**Issue by Kirkados** [TheElectricDream/SPOT#5]
If an experiment is started while the platform is floating, things to not go as intended (the pucks cycle on and off very fast). 

People either need to 1) remember to "Float off" before clicking "Start Experiment" (using some sort of prompt); 2) the "Start Experiment" button should automatically click "Float off" before actually starting the experiment (though it is sketchy to stop the platforms from floating without the user's knowledge because they might have some velocity); or 3) Simulink should be able to gracefully start an experiment when the pucks are in the "On" state.

If 3) is not possible/difficult, let's go for 1) where you a prompt the user to click "Float Off" before starting an experiment.

**Comment by TheElectricDream** [comment]
Resolved as of Hotfix 3.07b. Added many checks to ensure pucks are not ON. Still needs to be validated in the lab.

**Comment by TheElectricDream** [comment]
Added in GUI logic to check if pucks are running. If pucks are running when Run Experiment is selected, it should automatically shut them off.
