### ISSUE TITLE
Black simulated results aren't animated properly

### ISSUE THREAD

**Issue by Carleton-SRCL** [TheElectricDream/SPOT#6]
It looks like black stays at (0,0) when animating simulation results. 
![image](https://user-images.githubusercontent.com/80171095/113214067-f1618c00-9246-11eb-9b12-bfb4398bfa64.png)

**Comment by TheElectricDream** [comment]
Fixed as of Hotfix 3.07c. Issue was specific to the CombinedExperiment diagram. New data was added to the template file packet, which mean that when the GUI draws BLACK, it was pulling from the wrong array position.
