### ISSUE TITLE
Build, Deploy, & Start warning wording

### ISSUE THREAD

**Issue by Kirkados** [TheElectricDream/SPOT#8]
The "Warning, check that it says 'Build' in the Hardware tab," after clicking "Deploy Code" should be reworded or removed.

When I dismiss the warning, I still see "Build, Deploy, & Start" in the Hardware tab in Simulink.

Only once the build is complete does the Hardware tab switch to "Build Only".

Ideally, Simulink would show "Build Only" before it builds but it seems like that is a more difficult bug to fix. 

This warning could (possibly?!) be removed since it always seems to build without running now.

**Comment by TheElectricDream** [comment]
Resolved in version to be released soon.
